// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * EnvItem 环境变量配置项
 */
export class EnvItem {
    "key": string;
    "label": string;
    "value": string;
    "default_value": string;

    /**
     * text, number, bool, duration, select, password
     */
    "type": string;
    "group": string;
    "description": string;

    /**
     * select 类型的选项列表
     */
    "options"?: EnvSelectOption[];

    /**
     * 条件显示：当指定 key 的值等于 DependsOnValue 时显示
     */
    "depends_on"?: string;

    /**
     * DependsOn 匹配的值
     */
    "depends_value"?: string;

    /**
     * 是否需要重启生效
     */
    "restart_required": boolean;

    /** Creates a new EnvItem instance. */
    constructor($$source: Partial<EnvItem> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("value" in $$source)) {
            this["value"] = "";
        }
        if (!("default_value" in $$source)) {
            this["default_value"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("group" in $$source)) {
            this["group"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("restart_required" in $$source)) {
            this["restart_required"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EnvItem instance from a string or object.
     */
    static createFrom($$source: any = {}): EnvItem {
        const $$createField7_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField7_0($$parsedSource["options"]);
        }
        return new EnvItem($$parsedSource as Partial<EnvItem>);
    }
}

/**
 * EnvSelectOption 下拉选项
 */
export class EnvSelectOption {
    "value": string;
    "label": string;

    /** Creates a new EnvSelectOption instance. */
    constructor($$source: Partial<EnvSelectOption> = {}) {
        if (!("value" in $$source)) {
            this["value"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EnvSelectOption instance from a string or object.
     */
    static createFrom($$source: any = {}): EnvSelectOption {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EnvSelectOption($$parsedSource as Partial<EnvSelectOption>);
    }
}

// Private type creation functions
const $$createType0 = EnvSelectOption.createFrom;
const $$createType1 = $Create.Array($$createType0);
