// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * ActiveRequest 正在进行的请求信息
 */
export class ActiveRequest {
    "request_id": string;
    "provider_id": number;
    "provider": string;
    "model": string;
    "request_body": string;

    /**
     * 实时响应内容（流式逐字追加）
     */
    "response_content": string;

    /**
     * 实时工具调用列表
     */
    "tool_calls": ActiveToolCall[];

    /**
     * "pending" | "streaming" | "error"
     */
    "status": string;
    "start_time": time$0.Time;

    /**
     * "openai" | "anthropic" | "ollama"
     */
    "protocol": string;
    "client_ip": string;

    /** Creates a new ActiveRequest instance. */
    constructor($$source: Partial<ActiveRequest> = {}) {
        if (!("request_id" in $$source)) {
            this["request_id"] = "";
        }
        if (!("provider_id" in $$source)) {
            this["provider_id"] = 0;
        }
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("request_body" in $$source)) {
            this["request_body"] = "";
        }
        if (!("response_content" in $$source)) {
            this["response_content"] = "";
        }
        if (!("tool_calls" in $$source)) {
            this["tool_calls"] = [];
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("start_time" in $$source)) {
            this["start_time"] = null;
        }
        if (!("protocol" in $$source)) {
            this["protocol"] = "";
        }
        if (!("client_ip" in $$source)) {
            this["client_ip"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ActiveRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ActiveRequest {
        const $$createField6_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tool_calls" in $$parsedSource) {
            $$parsedSource["tool_calls"] = $$createField6_0($$parsedSource["tool_calls"]);
        }
        return new ActiveRequest($$parsedSource as Partial<ActiveRequest>);
    }
}

/**
 * ActiveToolCall 活跃请求中的工具调用信息
 */
export class ActiveToolCall {
    /**
     * tool_call id
     */
    "id": string;

    /**
     * function name
     */
    "name": string;

    /**
     * function arguments（逐步追加）
     */
    "arguments": string;

    /** Creates a new ActiveToolCall instance. */
    constructor($$source: Partial<ActiveToolCall> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("arguments" in $$source)) {
            this["arguments"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ActiveToolCall instance from a string or object.
     */
    static createFrom($$source: any = {}): ActiveToolCall {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ActiveToolCall($$parsedSource as Partial<ActiveToolCall>);
    }
}

// Private type creation functions
const $$createType0 = ActiveToolCall.createFrom;
const $$createType1 = $Create.Array($$createType0);
