// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppService Wails 绑定服务：代理控制、配置、系统信息
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../wailsapp/wails/v3/pkg/application/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "./internal/config/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ApplyDBConfig 运行时切换数据库配置
 */
export function ApplyDBConfig(params: $models.DBTestParams): $CancellablePromise<void> {
    return $Call.ByID(1298358398, params);
}

/**
 * EnvFileExists 检查 .env 文件是否存在
 */
export function EnvFileExists(): $CancellablePromise<boolean> {
    return $Call.ByID(1888069467);
}

/**
 * GetAutostartStatus 获取当前是否已注册开机自启动（以注册表/OS 配置为准）
 */
export function GetAutostartStatus(): $CancellablePromise<boolean> {
    return $Call.ByID(1609018541);
}

/**
 * GetDBFallbackMsg 获取数据库回退提示信息
 */
export function GetDBFallbackMsg(): $CancellablePromise<string> {
    return $Call.ByID(3501677775);
}

/**
 * GetEnvConfig 获取所有环境变量配置项
 */
export function GetEnvConfig(): $CancellablePromise<config$0.EnvItem[]> {
    return $Call.ByID(1972602283).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetLogHistory 获取全部运行日志（首次加载）
 */
export function GetLogHistory(): $CancellablePromise<$models.LogEntryVO[]> {
    return $Call.ByID(1797708668).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetNewLogs 获取增量运行日志（轮询）
 */
export function GetNewLogs(): $CancellablePromise<$models.LogEntryVO[]> {
    return $Call.ByID(4084258931).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetProxyStatus 获取代理服务状态
 */
export function GetProxyStatus(): $CancellablePromise<$models.ProxyStatusVO> {
    return $Call.ByID(3425455756).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GetVersion 获取应用版本号和构建时间
 */
export function GetVersion(): $CancellablePromise<{ [_ in string]?: string }> {
    return $Call.ByID(2729898890).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * HideMainWindow 隐藏主窗口
 */
export function HideMainWindow(): $CancellablePromise<void> {
    return $Call.ByID(387732299);
}

/**
 * LogDebug 前端调试日志
 */
export function LogDebug(msg: string): $CancellablePromise<void> {
    return $Call.ByID(2793403175, msg);
}

/**
 * LogError 前端错误日志
 */
export function LogError(msg: string): $CancellablePromise<void> {
    return $Call.ByID(1657314310, msg);
}

/**
 * LogInfo 前端信息日志
 */
export function LogInfo(msg: string): $CancellablePromise<void> {
    return $Call.ByID(2795377116, msg);
}

/**
 * LogWarn 前端警告日志
 */
export function LogWarn(msg: string): $CancellablePromise<void> {
    return $Call.ByID(3595790092, msg);
}

/**
 * SaveEnvConfig 保存环境变量配置到 .env 文件，并热更新内存中的可变配置
 */
export function SaveEnvConfig(items: { [_ in string]?: string }): $CancellablePromise<void> {
    return $Call.ByID(241746900, items);
}

/**
 * SetApp 保存 Wails App 引用，用于 Autostart 等 API
 */
export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(3487267257, app);
}

/**
 * SetAutostart 设置开机自启动（写入 .env + 更新操作系统注册）
 */
export function SetAutostart(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(1760948543, enabled);
}

/**
 * SetMainWindow 保存窗口引用，供 Show/Hide 使用
 */
export function SetMainWindow(w: application$0.WebviewWindow | null): $CancellablePromise<void> {
    return $Call.ByID(1412265083, w);
}

/**
 * ShowMainWindow 显示主窗口并置前
 */
export function ShowMainWindow(): $CancellablePromise<void> {
    return $Call.ByID(3326919698);
}

/**
 * StartProxy 启动代理服务
 */
export function StartProxy(): $CancellablePromise<void> {
    return $Call.ByID(2746353326);
}

/**
 * StopProxy 停止代理服务
 */
export function StopProxy(): $CancellablePromise<void> {
    return $Call.ByID(1140884718);
}

/**
 * TestDBConnection 测试数据库连接参数
 */
export function TestDBConnection(params: $models.DBTestParams): $CancellablePromise<$models.DBTestResultVO> {
    return $Call.ByID(626525936, params).then(($result: any) => {
        return $$createType6($result);
    });
}

// Private type creation functions
const $$createType0 = config$0.EnvItem.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.LogEntryVO.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $models.ProxyStatusVO.createFrom;
const $$createType5 = $Create.Map($Create.Any, $Create.Any);
const $$createType6 = $models.DBTestResultVO.createFrom;
