// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as handler$0 from "./internal/handler/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "./internal/model/models.js";

export const ActiveRequestVO = handler$0.ActiveRequest;
export type ActiveRequestVO = handler$0.ActiveRequest;

export class CodeBuddyResultVO {
    "message": string;
    "path": string;
    "exists": boolean;
    "added": boolean;
    "models": number;

    /** Creates a new CodeBuddyResultVO instance. */
    constructor($$source: Partial<CodeBuddyResultVO> = {}) {
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("exists" in $$source)) {
            this["exists"] = false;
        }
        if (!("added" in $$source)) {
            this["added"] = false;
        }
        if (!("models" in $$source)) {
            this["models"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CodeBuddyResultVO instance from a string or object.
     */
    static createFrom($$source: any = {}): CodeBuddyResultVO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CodeBuddyResultVO($$parsedSource as Partial<CodeBuddyResultVO>);
    }
}

/**
 * DBTestParams 数据库测试/应用参数
 */
export class DBTestParams {
    "db_type": string;
    "db_host": string;
    "db_port": string;
    "db_user": string;
    "db_pass": string;
    "db_name": string;
    "db_path": string;

    /** Creates a new DBTestParams instance. */
    constructor($$source: Partial<DBTestParams> = {}) {
        if (!("db_type" in $$source)) {
            this["db_type"] = "";
        }
        if (!("db_host" in $$source)) {
            this["db_host"] = "";
        }
        if (!("db_port" in $$source)) {
            this["db_port"] = "";
        }
        if (!("db_user" in $$source)) {
            this["db_user"] = "";
        }
        if (!("db_pass" in $$source)) {
            this["db_pass"] = "";
        }
        if (!("db_name" in $$source)) {
            this["db_name"] = "";
        }
        if (!("db_path" in $$source)) {
            this["db_path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DBTestParams instance from a string or object.
     */
    static createFrom($$source: any = {}): DBTestParams {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DBTestParams($$parsedSource as Partial<DBTestParams>);
    }
}

/**
 * DBTestResultVO 数据库测试结果
 */
export class DBTestResultVO {
    "success": boolean;
    "message": string;

    /** Creates a new DBTestResultVO instance. */
    constructor($$source: Partial<DBTestResultVO> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DBTestResultVO instance from a string or object.
     */
    static createFrom($$source: any = {}): DBTestResultVO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DBTestResultVO($$parsedSource as Partial<DBTestResultVO>);
    }
}

/**
 * HourlyStatBreakdownVO 分时详细拆分（堆叠图用），复用 model 层定义
 */
export const HourlyStatBreakdownVO = model$0.HourlyBreakdownItem;

/**
 * HourlyStatBreakdownVO 分时详细拆分（堆叠图用），复用 model 层定义
 */
export type HourlyStatBreakdownVO = model$0.HourlyBreakdownItem;

export class LogEntryVO {
    "time": string;
    "level": string;
    "message": string;

    /** Creates a new LogEntryVO instance. */
    constructor($$source: Partial<LogEntryVO> = {}) {
        if (!("time" in $$source)) {
            this["time"] = "";
        }
        if (!("level" in $$source)) {
            this["level"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogEntryVO instance from a string or object.
     */
    static createFrom($$source: any = {}): LogEntryVO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogEntryVO($$parsedSource as Partial<LogEntryVO>);
    }
}

/**
 * ModelStatVO 模型级别统计（前端用于计算成本）
 */
export class ModelStatVO {
    "date": string;
    "provider_id": number;
    "provider_name": string;
    "model": string;
    "total_input_tokens": number;
    "total_output_tokens": number;
    "total_tokens": number;
    "total_cached_tokens": number;
    "request_count": number;

    /** Creates a new ModelStatVO instance. */
    constructor($$source: Partial<ModelStatVO> = {}) {
        if (!("date" in $$source)) {
            this["date"] = "";
        }
        if (!("provider_id" in $$source)) {
            this["provider_id"] = 0;
        }
        if (!("provider_name" in $$source)) {
            this["provider_name"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("total_input_tokens" in $$source)) {
            this["total_input_tokens"] = 0;
        }
        if (!("total_output_tokens" in $$source)) {
            this["total_output_tokens"] = 0;
        }
        if (!("total_tokens" in $$source)) {
            this["total_tokens"] = 0;
        }
        if (!("total_cached_tokens" in $$source)) {
            this["total_cached_tokens"] = 0;
        }
        if (!("request_count" in $$source)) {
            this["request_count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModelStatVO instance from a string or object.
     */
    static createFrom($$source: any = {}): ModelStatVO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModelStatVO($$parsedSource as Partial<ModelStatVO>);
    }
}

export class ProviderCreateVO {
    "name": string;
    "auto_suffix": boolean;
    "url_suffix": string;
    "base_url": string;
    "api_key": string;
    "models": string;

    /** Creates a new ProviderCreateVO instance. */
    constructor($$source: Partial<ProviderCreateVO> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("auto_suffix" in $$source)) {
            this["auto_suffix"] = false;
        }
        if (!("url_suffix" in $$source)) {
            this["url_suffix"] = "";
        }
        if (!("base_url" in $$source)) {
            this["base_url"] = "";
        }
        if (!("api_key" in $$source)) {
            this["api_key"] = "";
        }
        if (!("models" in $$source)) {
            this["models"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProviderCreateVO instance from a string or object.
     */
    static createFrom($$source: any = {}): ProviderCreateVO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProviderCreateVO($$parsedSource as Partial<ProviderCreateVO>);
    }
}

export class ProviderUpdateVO {
    "name": string;
    "auto_suffix": boolean;
    "url_suffix": string;
    "base_url": string;
    "api_key": string;
    "models": string;

    /** Creates a new ProviderUpdateVO instance. */
    constructor($$source: Partial<ProviderUpdateVO> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("auto_suffix" in $$source)) {
            this["auto_suffix"] = false;
        }
        if (!("url_suffix" in $$source)) {
            this["url_suffix"] = "";
        }
        if (!("base_url" in $$source)) {
            this["base_url"] = "";
        }
        if (!("api_key" in $$source)) {
            this["api_key"] = "";
        }
        if (!("models" in $$source)) {
            this["models"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProviderUpdateVO instance from a string or object.
     */
    static createFrom($$source: any = {}): ProviderUpdateVO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProviderUpdateVO($$parsedSource as Partial<ProviderUpdateVO>);
    }
}

export class ProviderVO {
    "id": number;
    "name": string;
    "auto_suffix": boolean;
    "url_suffix": string;
    "base_url": string;
    "api_key": string;
    "models": string;
    "created_at": string;
    "updated_at": string;

    /** Creates a new ProviderVO instance. */
    constructor($$source: Partial<ProviderVO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("auto_suffix" in $$source)) {
            this["auto_suffix"] = false;
        }
        if (!("url_suffix" in $$source)) {
            this["url_suffix"] = "";
        }
        if (!("base_url" in $$source)) {
            this["base_url"] = "";
        }
        if (!("api_key" in $$source)) {
            this["api_key"] = "";
        }
        if (!("models" in $$source)) {
            this["models"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProviderVO instance from a string or object.
     */
    static createFrom($$source: any = {}): ProviderVO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProviderVO($$parsedSource as Partial<ProviderVO>);
    }
}

export class ProxyStatusVO {
    "status": string;
    "port": string;
    "error"?: string;

    /** Creates a new ProxyStatusVO instance. */
    constructor($$source: Partial<ProxyStatusVO> = {}) {
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProxyStatusVO instance from a string or object.
     */
    static createFrom($$source: any = {}): ProxyStatusVO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProxyStatusVO($$parsedSource as Partial<ProxyStatusVO>);
    }
}

export class RequestLogDetailVO {
    "id": number;
    "provider_id": number;
    "provider_name": string;
    "model": string;
    "input_tokens": number;
    "output_tokens": number;
    "total_tokens": number;
    "cached_tokens": number;
    "status": string;
    "error_message": string;
    "duration": number;
    "created_at": string;
    "response_content": string;
    "thinking_content": string;
    "request_body": string;
    "response_body": string;

    /** Creates a new RequestLogDetailVO instance. */
    constructor($$source: Partial<RequestLogDetailVO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("provider_id" in $$source)) {
            this["provider_id"] = 0;
        }
        if (!("provider_name" in $$source)) {
            this["provider_name"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("input_tokens" in $$source)) {
            this["input_tokens"] = 0;
        }
        if (!("output_tokens" in $$source)) {
            this["output_tokens"] = 0;
        }
        if (!("total_tokens" in $$source)) {
            this["total_tokens"] = 0;
        }
        if (!("cached_tokens" in $$source)) {
            this["cached_tokens"] = 0;
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("error_message" in $$source)) {
            this["error_message"] = "";
        }
        if (!("duration" in $$source)) {
            this["duration"] = 0;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }
        if (!("response_content" in $$source)) {
            this["response_content"] = "";
        }
        if (!("thinking_content" in $$source)) {
            this["thinking_content"] = "";
        }
        if (!("request_body" in $$source)) {
            this["request_body"] = "";
        }
        if (!("response_body" in $$source)) {
            this["response_body"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RequestLogDetailVO instance from a string or object.
     */
    static createFrom($$source: any = {}): RequestLogDetailVO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RequestLogDetailVO($$parsedSource as Partial<RequestLogDetailVO>);
    }
}

export class RequestLogVO {
    "id": number;
    "provider_id": number;
    "provider_name": string;
    "model": string;
    "input_tokens": number;
    "output_tokens": number;
    "total_tokens": number;
    "cached_tokens": number;
    "status": string;
    "error_message": string;
    "duration": number;
    "created_at": string;

    /** Creates a new RequestLogVO instance. */
    constructor($$source: Partial<RequestLogVO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("provider_id" in $$source)) {
            this["provider_id"] = 0;
        }
        if (!("provider_name" in $$source)) {
            this["provider_name"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("input_tokens" in $$source)) {
            this["input_tokens"] = 0;
        }
        if (!("output_tokens" in $$source)) {
            this["output_tokens"] = 0;
        }
        if (!("total_tokens" in $$source)) {
            this["total_tokens"] = 0;
        }
        if (!("cached_tokens" in $$source)) {
            this["cached_tokens"] = 0;
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("error_message" in $$source)) {
            this["error_message"] = "";
        }
        if (!("duration" in $$source)) {
            this["duration"] = 0;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RequestLogVO instance from a string or object.
     */
    static createFrom($$source: any = {}): RequestLogVO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RequestLogVO($$parsedSource as Partial<RequestLogVO>);
    }
}

export class SessionVO {
    "id": number;
    "models": string;
    "request_count": number;
    "total_tokens": number;
    "total_cost": number;
    "created_at": string;
    "updated_at": string;

    /** Creates a new SessionVO instance. */
    constructor($$source: Partial<SessionVO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("models" in $$source)) {
            this["models"] = "";
        }
        if (!("request_count" in $$source)) {
            this["request_count"] = 0;
        }
        if (!("total_tokens" in $$source)) {
            this["total_tokens"] = 0;
        }
        if (!("total_cost" in $$source)) {
            this["total_cost"] = 0;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionVO instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionVO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionVO($$parsedSource as Partial<SessionVO>);
    }
}
