// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ProviderService Wails 绑定服务：Provider 管理
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateProvider 创建 Provider
 */
export function CreateProvider(data: $models.ProviderCreateVO): $CancellablePromise<$models.ProviderVO> {
    return $Call.ByID(1841495485, data).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * DeleteProvider 删除 Provider
 */
export function DeleteProvider(id: number): $CancellablePromise<void> {
    return $Call.ByID(4291218382, id);
}

/**
 * ExportProvidersToFile 导出到文件（使用 SaveFileDialog）
 */
export function ExportProvidersToFile(): $CancellablePromise<string> {
    return $Call.ByID(368123083);
}

/**
 * FetchProviderModels 查询上游 API 的所有可用模型（OpenAI 兼容格式：GET /v1/models）
 */
export function FetchProviderModels(baseURL: string, apiKey: string): $CancellablePromise<string[]> {
    return $Call.ByID(2082254471, baseURL, apiKey).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetProvider 获取单个 Provider（API Key 脱敏）
 */
export function GetProvider(id: number): $CancellablePromise<$models.ProviderVO> {
    return $Call.ByID(2555477485, id).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetProviders 获取所有 Provider（API Key 脱敏）
 */
export function GetProviders(): $CancellablePromise<$models.ProviderVO[]> {
    return $Call.ByID(1716043706).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * ImportProvidersFromFile 从文件导入（使用 OpenFileDialog）
 */
export function ImportProvidersFromFile(): $CancellablePromise<void> {
    return $Call.ByID(2172146215);
}

/**
 * SetupCodeBuddy 配置 CodeBuddy models.json
 */
export function SetupCodeBuddy(): $CancellablePromise<$models.CodeBuddyResultVO> {
    return $Call.ByID(2095616408).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * TestProviderConnection 测试 Provider 连接是否可用
 */
export function TestProviderConnection(baseURL: string, apiKey: string, model: string, urlSuffix: string, autoSuffix: boolean): $CancellablePromise<string> {
    return $Call.ByID(714870721, baseURL, apiKey, model, urlSuffix, autoSuffix);
}

/**
 * UpdateProvider 更新 Provider（含 API Key 保留逻辑）
 */
export function UpdateProvider(id: number, data: $models.ProviderUpdateVO): $CancellablePromise<$models.ProviderVO> {
    return $Call.ByID(2458498924, id, data).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.ProviderVO.createFrom;
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = $Create.Array($$createType0);
const $$createType3 = $models.CodeBuddyResultVO.createFrom;
