// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * StatsService Wails 绑定服务：统计和日志
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as handler$0 from "./internal/handler/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "./internal/model/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetActiveRequest 按 ID 获取单个活跃请求
 */
export function GetActiveRequest(requestID: string): $CancellablePromise<$models.ActiveRequestVO> {
    return $Call.ByID(21038881, requestID).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetActiveRequests 获取当前活跃请求
 */
export function GetActiveRequests(): $CancellablePromise<$models.ActiveRequestVO[]> {
    return $Call.ByID(1264485910).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetDailyStats 获取 30 天每日统计
 */
export function GetDailyStats(providerID: number): $CancellablePromise<model$0.TokenStats[]> {
    return $Call.ByID(2006612670, providerID).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetHourlyStatsByDate 获取分时统计
 */
export function GetHourlyStatsByDate(date: string, providerID: number): $CancellablePromise<model$0.HourlyStatsResult[]> {
    return $Call.ByID(3410132755, date, providerID).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetHourlyStatsByDateWithBreakdown 获取按 provider 拆分的分时统计（用于堆叠图）
 */
export function GetHourlyStatsByDateWithBreakdown(date: string): $CancellablePromise<$models.HourlyStatBreakdownVO[]> {
    return $Call.ByID(3542509878, date).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * GetLogDetail 获取单条请求日志详情
 */
export function GetLogDetail(id: number): $CancellablePromise<$models.RequestLogDetailVO> {
    return $Call.ByID(1855908077, id).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * GetRecentLogs 获取最近请求日志
 */
export function GetRecentLogs(limit: number): $CancellablePromise<$models.RequestLogVO[]> {
    return $Call.ByID(3158810798, limit).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * GetStats 获取仪表盘统计
 */
export function GetStats(providerID: number): $CancellablePromise<{ [_ in string]?: model$0.TokenStats | null }> {
    return $Call.ByID(802081133, providerID).then(($result: any) => {
        return $$createType12($result);
    });
}

// Private type creation functions
const $$createType0 = handler$0.ActiveRequest.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = model$0.TokenStats.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = model$0.HourlyStatsResult.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $models.HourlyStatBreakdownVO.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = $models.RequestLogDetailVO.createFrom;
const $$createType9 = $models.RequestLogVO.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = $Create.Nullable($$createType2);
const $$createType12 = $Create.Map($Create.Any, $$createType11);
