// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * StatsService Wails 绑定服务：统计和日志
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as handler$0 from "./internal/handler/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "./internal/model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as repository$0 from "./internal/repository/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetActiveRequest 按 ID 获取单个活跃请求
 */
export function GetActiveRequest(requestID: string): $CancellablePromise<$models.ActiveRequestVO> {
    return $Call.ByID(21038881, requestID).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetActiveRequests 获取当前活跃请求
 */
export function GetActiveRequests(): $CancellablePromise<$models.ActiveRequestVO[]> {
    return $Call.ByID(1264485910).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetDailyStats 获取 30 天每日统计
 */
export function GetDailyStats(providerID: number): $CancellablePromise<model$0.TokenStats[]> {
    return $Call.ByID(2006612670, providerID).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetHourlyModelStats 获取指定日期指定模型的分时统计
 */
export function GetHourlyModelStats(date: string, providerID: number, modelName: string): $CancellablePromise<model$0.HourlyStatsResult[]> {
    return $Call.ByID(3859796019, date, providerID, modelName).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetHourlyStatsByDate 获取分时统计
 */
export function GetHourlyStatsByDate(date: string, providerID: number): $CancellablePromise<model$0.HourlyStatsResult[]> {
    return $Call.ByID(3410132755, date, providerID).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetHourlyStatsByDateWithBreakdown 获取按 provider+model 拆分的分时统计（用于堆叠图）
 * providerID=0 时返回所有 provider 的数据，providerID>0 时只返回指定 provider 的数据
 */
export function GetHourlyStatsByDateWithBreakdown(date: string, providerID: number): $CancellablePromise<$models.HourlyStatBreakdownVO[]> {
    return $Call.ByID(3542509878, date, providerID).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * GetLogDetail 获取单条请求日志详情
 */
export function GetLogDetail(id: number): $CancellablePromise<$models.RequestLogDetailVO> {
    return $Call.ByID(1855908077, id).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * GetModelStats 获取模型级别统计（用于前端计算成本）
 */
export function GetModelStats(providerID: number): $CancellablePromise<$models.ModelStatVO[]> {
    return $Call.ByID(1616811742, providerID).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * GetRecentLogs 获取最近请求日志，modelName 非空时按模型名过滤
 */
export function GetRecentLogs(limit: number, modelName: string): $CancellablePromise<$models.RequestLogVO[]> {
    return $Call.ByID(3158810798, limit, modelName).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * GetSessionRequests 获取指定会话的请求列表
 */
export function GetSessionRequests(sessionID: number): $CancellablePromise<$models.RequestLogVO[]> {
    return $Call.ByID(1969007868, sessionID).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * GetSessions 获取所有会话列表（按创建时间倒序）
 */
export function GetSessions(): $CancellablePromise<$models.SessionVO[]> {
    return $Call.ByID(1294167451).then(($result: any) => {
        return $$createType14($result);
    });
}

/**
 * GetStats 获取仪表盘统计
 */
export function GetStats(providerID: number): $CancellablePromise<{ [_ in string]?: model$0.TokenStats | null }> {
    return $Call.ByID(802081133, providerID).then(($result: any) => {
        return $$createType16($result);
    });
}

/**
 * WithSessionRepo 设置会话仓库（启用会话统计查询）
 */
export function WithSessionRepo(repo: repository$0.ChatSessionRepository | null): $CancellablePromise<void> {
    return $Call.ByID(2027830862, repo);
}

// Private type creation functions
const $$createType0 = handler$0.ActiveRequest.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = model$0.TokenStats.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = model$0.HourlyStatsResult.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = model$0.HourlyBreakdownItem.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = $models.RequestLogDetailVO.createFrom;
const $$createType9 = $models.ModelStatVO.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = $models.RequestLogVO.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = $models.SessionVO.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = $Create.Nullable($$createType2);
const $$createType16 = $Create.Map($Create.Any, $$createType15);
