// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * HourlyStatsResult 分时统计结果
 */
export class HourlyStatsResult {
    "hour": number;
    "request_count": number;
    "total_tokens": number;
    "input_tokens": number;
    "output_tokens": number;
    "cached_tokens": number;

    /** Creates a new HourlyStatsResult instance. */
    constructor($$source: Partial<HourlyStatsResult> = {}) {
        if (!("hour" in $$source)) {
            this["hour"] = 0;
        }
        if (!("request_count" in $$source)) {
            this["request_count"] = 0;
        }
        if (!("total_tokens" in $$source)) {
            this["total_tokens"] = 0;
        }
        if (!("input_tokens" in $$source)) {
            this["input_tokens"] = 0;
        }
        if (!("output_tokens" in $$source)) {
            this["output_tokens"] = 0;
        }
        if (!("cached_tokens" in $$source)) {
            this["cached_tokens"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HourlyStatsResult instance from a string or object.
     */
    static createFrom($$source: any = {}): HourlyStatsResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HourlyStatsResult($$parsedSource as Partial<HourlyStatsResult>);
    }
}

/**
 * TokenStats Token使用统计
 */
export class TokenStats {
    "date": string;
    "total_input_tokens": number;
    "total_output_tokens": number;
    "total_tokens": number;
    "total_cached_tokens": number;
    "request_count": number;

    /** Creates a new TokenStats instance. */
    constructor($$source: Partial<TokenStats> = {}) {
        if (!("date" in $$source)) {
            this["date"] = "";
        }
        if (!("total_input_tokens" in $$source)) {
            this["total_input_tokens"] = 0;
        }
        if (!("total_output_tokens" in $$source)) {
            this["total_output_tokens"] = 0;
        }
        if (!("total_tokens" in $$source)) {
            this["total_tokens"] = 0;
        }
        if (!("total_cached_tokens" in $$source)) {
            this["total_cached_tokens"] = 0;
        }
        if (!("request_count" in $$source)) {
            this["request_count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TokenStats instance from a string or object.
     */
    static createFrom($$source: any = {}): TokenStats {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TokenStats($$parsedSource as Partial<TokenStats>);
    }
}
