// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ChatSessionRepository {

    /** Creates a new ChatSessionRepository instance. */
    constructor($$source: Partial<ChatSessionRepository> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatSessionRepository instance from a string or object.
     */
    static createFrom($$source: any = {}): ChatSessionRepository {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChatSessionRepository($$parsedSource as Partial<ChatSessionRepository>);
    }
}
