// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateProvider(arg1) {
  return window['go']['main']['App']['CreateProvider'](arg1);
}

export function DeleteProvider(arg1) {
  return window['go']['main']['App']['DeleteProvider'](arg1);
}

export function EnvFileExists() {
  return window['go']['main']['App']['EnvFileExists']();
}

export function ExportProvidersToFile() {
  return window['go']['main']['App']['ExportProvidersToFile']();
}

export function GetActiveRequest(arg1) {
  return window['go']['main']['App']['GetActiveRequest'](arg1);
}

export function GetActiveRequests() {
  return window['go']['main']['App']['GetActiveRequests']();
}

export function GetDailyStats() {
  return window['go']['main']['App']['GetDailyStats']();
}

export function GetEnvConfig() {
  return window['go']['main']['App']['GetEnvConfig']();
}

export function GetHourlyStatsByDate(arg1) {
  return window['go']['main']['App']['GetHourlyStatsByDate'](arg1);
}

export function GetLogDetail(arg1) {
  return window['go']['main']['App']['GetLogDetail'](arg1);
}

export function GetLogHistory() {
  return window['go']['main']['App']['GetLogHistory']();
}

export function GetNewLogs() {
  return window['go']['main']['App']['GetNewLogs']();
}

export function GetProvider(arg1) {
  return window['go']['main']['App']['GetProvider'](arg1);
}

export function GetProviders() {
  return window['go']['main']['App']['GetProviders']();
}

export function GetProxyStatus() {
  return window['go']['main']['App']['GetProxyStatus']();
}

export function GetRecentLogs(arg1) {
  return window['go']['main']['App']['GetRecentLogs'](arg1);
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function ImportProvidersFromFile() {
  return window['go']['main']['App']['ImportProvidersFromFile']();
}

export function SaveEnvConfig(arg1) {
  return window['go']['main']['App']['SaveEnvConfig'](arg1);
}

export function SetupCodeBuddy() {
  return window['go']['main']['App']['SetupCodeBuddy']();
}

export function StartProxy() {
  return window['go']['main']['App']['StartProxy']();
}

export function StopProxy() {
  return window['go']['main']['App']['StopProxy']();
}

export function UpdateProvider(arg1, arg2) {
  return window['go']['main']['App']['UpdateProvider'](arg1, arg2);
}
