// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {handler} from '../models';
import {model} from '../models';
import {config} from '../models';

export function CreateProvider(arg1:main.ProviderCreateVO):Promise<main.ProviderVO>;

export function DeleteProvider(arg1:number):Promise<void>;

export function EnvFileExists():Promise<boolean>;

export function ExportProvidersToFile():Promise<string>;

export function FetchProviderModels(arg1:string,arg2:string):Promise<Array<string>>;

export function GetActiveRequest(arg1:string):Promise<handler.ActiveRequest>;

export function GetActiveRequests():Promise<Array<handler.ActiveRequest>>;

export function GetDBFallbackMsg():Promise<string>;

export function GetDailyStats():Promise<Array<model.TokenStats>>;

export function GetEnvConfig():Promise<Array<config.EnvItem>>;

export function GetHourlyStatsByDate(arg1:string):Promise<Array<model.HourlyStatsResult>>;

export function GetLogDetail(arg1:number):Promise<main.RequestLogDetailVO>;

export function GetLogHistory():Promise<Array<main.LogEntryVO>>;

export function GetNewLogs():Promise<Array<main.LogEntryVO>>;

export function GetProvider(arg1:number):Promise<main.ProviderVO>;

export function GetProviders():Promise<Array<main.ProviderVO>>;

export function GetProxyStatus():Promise<main.ProxyStatusVO>;

export function GetRecentLogs(arg1:number):Promise<Array<main.RequestLogVO>>;

export function GetStats():Promise<Record<string, model.TokenStats>>;

export function GetVersion():Promise<Record<string, string>>;

export function ImportProvidersFromFile():Promise<void>;

export function SaveEnvConfig(arg1:Record<string, string>):Promise<void>;

export function SetupCodeBuddy():Promise<main.CodeBuddyResultVO>;

export function StartProxy():Promise<void>;

export function StopProxy():Promise<void>;

export function TestProviderConnection(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<string>;

export function UpdateProvider(arg1:number,arg2:main.ProviderUpdateVO):Promise<main.ProviderVO>;
